global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    
  - job_name: 'market-data-service'
    static_configs:
      - targets: ['market-data-service:8000']
