apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  local-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      wal:
        enabled: true
        dir: /loki/wal

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            interval: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        shared_dir: /loki/boltdb-shipper

      filesystem:
        directory: /loki/chunks