apiVersion: v1
kind: Service
metadata:
  name: market-data-service-service
spec:
  selector:
    app: market-data-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP