apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service
  labels:
    app: market-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data-service
  template:
    metadata:
      labels:
        app: market-data-service
    spec:
      containers:
      - name: market-data-service
        image: gcr.io/fintech-trading-platform-2025/market-data-service
        ports:
        - containerPort: 8000