apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

      memory_limiter:
        check_interval: 1s
        limit_mib: 1500
        spike_limit_mib: 512

      attributes:
        actions:
          - key: environment
            value: "production"
            action: insert

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "fintech"
        const_labels:
          platform: "trading"
        send_timestamps: true
        metric_expiration: 180m

      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
        format: json
        labels:
          resource:
            service.name: "service_name"
            environment: "environment"

      otlp/tempo:
        endpoint: tempo:4317
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, attributes]
          exporters: [prometheus]
        
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, attributes]
          exporters: [loki]
        
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, attributes]
          exporters: [otlp/tempo]

      telemetry:
        logs:
          level: "debug"