apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks

    compactor:
      compaction:
        block_retention: 24h