apiVersion: v1
kind: Service
metadata:
  name: tempo-service
spec:
  selector:
    app: tempo
  ports:
  - protocol: TCP
    name: grpc
    port: 14250
    targetPort: 14250
  - protocol: TCP
    name: http
    port: 3200
    targetPort: 3200
  type: ClusterIP